### ISSUE TITLE
CNCF TAG Runtime Discussion/Presentation

### ISSUE THREAD

**Issue by rajaskakodkar** [edgelesssys/contrast#525]
Hello Contrast maintainers,

We at CNCF TAG Runtime which is the Technical Advisory Group for workload execution on cloud native infrastructure are very much interested to hear about Contrast and its take on Confidential Containers. 

As the Tech Lead of [CNCF TAG Runtime](https://github.com/cncf/tag-runtime), I am reaching out to you to present Contrast at one of our meetings. We would love to hear about the project roadmap and an overview of Contrast.

We have slots available on:

[the TAG Runtime biweekly meeting](https://docs.google.com/document/d/1k7VNetgbuDNyIs_87GLQRH2W5SLgjgOhB6pDyv89MYk/edit#heading=h.9f2t9chnw0yh)

If you are interested, please feel free to add it to the agenda or reach out to us in the [#tag-runtime](https://slack.cncf.io/) channel on the CNCF slack.

Thanks!

cc: @raravena80

**Comment by katexochen** [comment]
Hi @rajaskakodkar, thanks for the kind invitation! We are happy to present Contrast, we've added us to the meeting on 20th of June.

**Comment by rajaskakodkar** [comment]
Thank you @katexochen !
