### ISSUE TITLE
0.7.0: contrast generate deployment/ ignores the vote-bot Deployment in the emojivoto example

### ISSUE THREAD

**Issue by blenessy** [edgelesssys/contrast#588]
Using contrast v0.7.0 I tried the emojivoto example again. Everything went smooth (according to the [documentation][1]) except that the vote-bot pod never started (confirmed with k9s). 

A quick check in `emojivoto-demo.yaml` (attached) reveals that the `io.katacontainers.config.agent.policy` is missing from the vote-bot `Deployment`. Is the vote-bot Deployment suppose to be part of the TCB or not? In the [documentation][1] it is rendered in a different color (yellow), which suggests that it is NOT suppose to be trusted. Either way it is not starting properly.

[1]: https://docs.edgeless.systems/contrast/examples/emojivoto

[emojivoto-demo.yml.gz](https://github.com/user-attachments/files/15864780/emojivoto-demo.yml.gz)

**Comment by katexochen** [comment]
The vote-bot in the demo simulates a user of the public service, and is not part of the confidential deployment. As such, it doesn't need a policy, and it also doesn't have a runtimeClass set.

Previous to v0.7.0, the policy generation tool hadn't had the ability to filter for runtime class when annotating policies, and thus would even add a policy to the bot, even when it didn't have the Contrast runtimeClass. This is now fixed.

Now trying to understand why the bot isn't starting for you. Can you provide any pod logs/ pods description?

**Comment by blenessy** [comment]
Hold off please @katexochen . It seems to have started now. It was lagging (minutes) vs the other nodes.
I'll try to investigate why the lag occurred ...

**Comment by blenessy** [comment]
Managed to dump all logs.

[logs.tgz](https://github.com/user-attachments/files/15866094/logs.tgz)

**Comment by blenessy** [comment]
When trying to reproduce in a fresh AKS cluster, the `vote-bot` got deployed in `nodegroup2` - like the rest of the services and it worked immediately. In my first attempt it got deployed to `nodegroup1`.

**Comment by katexochen** [comment]
> When trying to reproduce in a fresh AKS cluster, the `vote-bot` got deployed in `nodegroup2` - like the rest of the services and it worked immediately. In my first attempt it got deployed to `nodegroup1`.

As the pod does not have any specific requirements, it's fine for Kubernetes to schedule it on either node group 1 or 2.

**Comment by blenessy** [comment]
As nothing points to a problem in contrast - I'm closing this issue.

**Comment by katexochen** [comment]
Thanks for the report anyway @blenessy. :)
