### ISSUE TITLE
Bump Kata Containers to its 3.10.1 (to be released soon) version, or bring in the following two patches

### ISSUE THREAD

**Issue by fidencio** [edgelesssys/contrast#953]
* Properly set hostname inside the container:
  * https://github.com/kata-containers/kata-containers/commit/3dabe0f5f080651c38720600082a72f0e0d1d1be
  * The lack of this one breaks several apps (seen this mostly with Java apps) which rely on the container hostname being set
* Properly set the permissions for devices inside the container
  * https://github.com/kata-containers/kata-containers/commit/322846b36f63fd30b4da33165e7191744e583b35

**Comment by katexochen** [comment]
Thanks for the head up! Upgrade to 3.10.0 is on my todo list, will wait for 3.10.1 then so I only have to rebase our patch set once. :)
